DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE CLIENTES (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
	,NOME VARCHAR(70) NOT NULL DEFAULT ''
	,CPF CHAR(11) NOT NULL DEFAULT ''
	,IDADE INT NOT NULL DEFAULT '0'
	,ALTURA DECIMAL(3,2) DEFAULT '0'
);


INSERT INTO CLIENTES (NOME, CPF, IDADE, ALTURA) 
VALUES ('MATEUS DE FREITAS', '17770459087', '27', '1.66'); 

INSERT INTO CLIENTES (NOME, CPF, IDADE, ALTURA) 
VALUES ('JOAO DE FREITAS', '27770459087', '28', '1.99'); 


UPDATE CLIENTES SET NOME = 'JOAO CARLOS' WHERE CPF = '27770459087';

DELETE FROM CLIENTES WHERE CPF = '27770459087';

SELECT * FROM CLIENTES;


-- TABELA CEMITERIO


DROP TABLE IF EXISTS CEMITERIO;

CREATE TABLE CEMITERIO (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
	,TIPO VARCHAR(7) NOT NULL DEFAULT ''
	,LOTE VARCHAR(20) NOT NULL DEFAULT ''
	,CPF CHAR(11) DEFAULT ''
	,DATAMORTE DATE DEFAULT NULL
	,DATANASCIMENTO DATE DEFAULT NULL
	,VALORALUGUEL DECIMAL(10,2) NOT NULL DEFAULT 0.00
	,NOMEMORTO VARCHAR(70) DEFAULT ''
);


INSERT INTO CEMITERIO (TIPO, LOTE, CPF, DATAMORTE, DATANASCIMENTO, VALORALUGUEL, NOMEMORTO)
VALUES ('TUMULO', 'L1C2', '17770459087', '2026-08-26', '2007-09-11', 100.78, 'JORGE');

INSERT INTO CEMITERIO (TIPO, LOTE, VALORALUGUEL)
VALUES ('GAVETA', 'L3G4', 100.78);

SELECT * FROM cemiterio;

-- 01/09/2026

DROP TABLE IF EXISTS jogadores, clubes;

CREATE TABLE CLUBES (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
	,NOME VARCHAR(70) NOT NULL UNIQUE
	,DATACRIACAO DATE NOT NULL
	,NOMEPRESIDENTE VARCHAR(70) NULL 
	,ESTADIO VARCHAR(70) NULL
	,VALORFOLHA DECIMAL(13,2) NOT NULL DEFAULT '0.00'
);


CREATE TABLE JOGADORES (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
	,IDCLUBE INT NULL
	,NOME VARCHAR(70) NOT NULL
	,SALARIO DECIMAL(10,2) NULL DEFAULT '0.0'
	,DATANASCIMENTO DATE NOT NULL
	,DATACONTRATACAO DATE
	,FOREIGN KEY (IDCLUBE) REFERENCES clubes(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO CLUBES (NOME, DATACRIACAO, NOMEPRESIDENTE, ESTADIO, VALORFOLHA)
VALUES ('Esporte Clube Novo Hamburgo', '1911-05-01', 'Jerônimo Freitas', 'Estádio do Vale', '180000');

SELECT * FROM CLUBES;

INSERT INTO JOGADORES (IDCLUBE, NOME, SALARIO, DATANASCIMENTO, DATACONTRATACAO)
VALUES (1, 'Breno Boeno', '1621', '2002-04-17', '2025-04-14');

SELECT * FROM JOGADORES;

SELECT C.NOME, J.IDCLUBE, J.NOME, J.SALARIO FROM JOGADORES J INNER JOIN CLUBES C ON J.IDCLUBE = C.ID;

-- 02/09/2026

INSERT INTO clubes 
	(ID, NOME, DATACRIACAO, NOMEPRESIDENTE, ESTADIO, VALORFOLHA)
VALUES
	(NULL, 'GREMIO-GRE', '1912-03-12', 'JOAO PAULO', 'OLIMPICO', '1545678,00'),
	(NULL, 'INTERNACIONAL-INT', '1908-07-11', 'MARIO CERTA', 'BEIRA RIO', '25678,00');
	
SELECT * FROM CLUBES;

INSERT INTO jogadores 
	(IDCLUBE, NOME, SALARIO, DATANASCIMENTO, DATACONTRATACAO)
VALUES 
	(1, 'Breno Boeno', '1621', '2002-04-17', '2025-04-14'),
	(1, 'Pedro Paulo', '33621', '2000-02-27', '2022-02-12'),
	(2, 'Cesar Augusto', '4458', '2004-04-14', '2024-06-17'),
	(2, 'Antonio Moraes', '12458', '1999-09-19', '2024-09-19'),
	(3, 'José Carlos', '22358', '1998-08-18', '2022-09-19'),
	(3, 'Calos Marques', '42358', '2003-03-13', '2023-09-19');
	
SELECT * FROM jogadores;

DELETE FROM jogadores WHERE ID = 4;



-- 08/09/2026

-- limpar tabelas

DELETE FROM jogadores WHERE IDCLUBE IN (1, 2, 3);

DELETE FROM clubes WHERE 1=1;

SELECT * FROM clubes;

SELECT * FROM jogadores;


-- Copiar tabela basileirao

-- USA O SEU DATABASE
USE a151570; 

-- DELETA A TABELA TEMPORARIA TBRAS, CASO EXISTIR
DROP TEMPORARY TABLE IF EXISTS TBRAS; 

-- CRIA UMA COPIA TEMPORARIA DA TABELA DO BRASILEIRAO
CREATE TEMPORARY TABLE TBRAS LIKE REFERENCIAS.BRASILEIRAO2018; 

-- INSERE TODOS OS REGISTROS DA TABELA ORIGINAL, NA NOVA TABELA
INSERT INTO TBRAS SELECT * FROM REFERENCIAS.BRASILEIRAO2018; 

SELECT * FROM TBRAS;


-- SABER SE TEM ALGUMA VANTAGEM EM SER MANDANTE
-- QUANTOS TIMES GANHARAM SENDO MANDANTE E QUANTOS GANHARAM SENDO VISITANTE

SELECT COUNT(*) MANDANTEGANHOU FROM TBRAS WHERE MANDANTEGOLS > VISITANTEGOLS;

SELECT COUNT(*) VISITANTEGANHOU FROM TBRAS WHERE MANDANTEGOLS < VISITANTEGOLS;


-- VARIAVEIS DE SEÇÃO
SELECT COUNT(*) INTO @MANDANTEGANHOU FROM TBRAS WHERE MANDANTEGOLS > VISITANTEGOLS;
SELECT COUNT(*) INTO @VISITANTEGANHOU FROM TBRAS WHERE MANDANTEGOLS < VISITANTEGOLS;

SELECT @MANDANTEGANHOU, @VISITANTEGANHOU, (@MANDANTEGANHOU / @VISITANTEGANHOU) PROPORCAO;



-- 09/09/2026


-- SOMAR TODOS OS PONTOS

-- 1. Cria a tabela acumuladora
DROP TEMPORARY TABLE IF EXISTS TMP_PONTUACAO;
CREATE TEMPORARY TABLE TMP_PONTUACAO (
    CLUBE VARCHAR(100),
    PONTOS INT
);

-- 2. Insere os pontos dos mandantes
INSERT INTO TMP_PONTUACAO
SELECT 
    MANDANTE,
    CASE 
        WHEN MANDANTEGOLS > VISITANTEGOLS THEN 3
        WHEN MANDANTEGOLS = VISITANTEGOLS THEN 1
        ELSE 0
    END
FROM TBRAS;

-- 3. Insere os pontos dos visitantes
INSERT INTO TMP_PONTUACAO
SELECT 
    VISITANTE,
    CASE 
        WHEN VISITANTEGOLS > MANDANTEGOLS THEN 3
        WHEN VISITANTEGOLS = MANDANTEGOLS THEN 1
        ELSE 0
    END
FROM TBRAS;

-- 4. Agrupa o resultado final
SELECT 
    CLUBE, 
    SUM(PONTOS) AS TOTAL_PONTOS
FROM TMP_PONTUACAO
GROUP BY CLUBE
ORDER BY TOTAL_PONTOS DESC;




-- SELECT COM 2 ORDERBY
SELECT * FROM TBRAS ORDER BY MANDANTEGOLS DESC, VISITANTEGOLS ASC;


-- SALDO DE GOLS DO MANDANTE
SELECT MANDANTE, (MANDANTEGOLS - VISITANTEGOLS) AS SG FROM TBRAS ORDER BY SG DESC;


-- SALDO DE GOLS DO VISITANTE
SELECT VISITANTE, (VISITANTEGOLS - MANDANTEGOLS) AS SG FROM TBRAS ORDER BY SG DESC;


-- QUAIS VISITANTES QUE FIZERAM MAIOR DIFERENÇA DE GOLS EM UM UNICO JOGO
SELECT * FROM TBRAS ORDER BY (VISITANTEGOLS - MANDANTEGOLS) DESC;




-- TIRAR 3 PTS DO CORINTHIANS - SP E DAR 3 PRONTOS PARA PALMEIRAS - SP

SELECT * FROM TBRAS WHERE MANDANTE = 'CORINTHIANS - SP' AND VISITANTE = 'PALMEIRAS - SP';

SELECT * FROM TBRAS WHERE VISITANTE = 'CORINTHIANS - SP' AND MANDANTE = 'PALMEIRAS - SP';

UPDATE TBRAS SET MANDANTEGOLS = 0, VISITANTEGOLS = 1 WHERE JOGO = 47;

SELECT * FROM TBRAS WHERE JOGO = 47;


-- TIRAR 3 PTS DO ATLÉTICO - MG E DAR 3 PTS PRO CRUZEIRO - MG

SELECT * FROM TBRAS WHERE MANDANTE = 'ATLÉTICO - MG' AND VISITANTE = 'CRUZEIRO - MG';

UPDATE TBRAS SET MANDANTEGOLS = 0, VISITANTEGOLS = 1 WHERE JOGO = 51;

SELECT * FROM TBRAS WHERE JOGO = 51;


-- QUANTIDADE DE JOGOS EM CADA ESTÁDIO

SELECT 
    LOCAL, 
    COUNT(*) AS TOTAL_JOGOS
FROM TBRAS
GROUP BY LOCAL
ORDER BY TOTAL_JOGOS DESC;


-- QUANTIDADE MÉDIA DE GOL EM CADA ESTÁDIO

SELECT 
    LOCAL, 
    COUNT(*) AS TOTAL_JOGOS,
    AVG(MANDANTEGOLS + VISITANTEGOLS) AS MEDIA_GOLS
FROM TBRAS
GROUP BY LOCAL
ORDER BY MEDIA_GOLS DESC;

-- DESVIO PADRAO DE GOL EM CADA ESTÁDIO

SELECT 
    LOCAL, 
    COUNT(*) AS TOTAL_JOGOS,
    AVG(MANDANTEGOLS + VISITANTEGOLS) AS MEDIA_GOLS,
    STD(MANDANTEGOLS + VISITANTEGOLS) AS DESVIO_PADRAO
FROM TBRAS
GROUP BY LOCAL
ORDER BY DESVIO_PADRAO DESC;
