DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE CLIENTES (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
	,NOME VARCHAR(70) NOT NULL DEFAULT ''
	,CPF CHAR(11) NOT NULL DEFAULT ''
	,IDADE INT NOT NULL DEFAULT '0'
	,ALTURA DECIMAL(3,2) DEFAULT '0'
);


INSERT INTO CLIENTES (NOME, CPF, IDADE, ALTURA) 
VALUES ('MATEUS DE FREITAS', '17770459087', '27', '1.66'); 

INSERT INTO CLIENTES (NOME, CPF, IDADE, ALTURA) 
VALUES ('JOAO DE FREITAS', '27770459087', '28', '1.99'); 


UPDATE CLIENTES SET NOME = 'JOAO CARLOS' WHERE CPF = '27770459087';

DELETE FROM CLIENTES WHERE CPF = '27770459087';

SELECT * FROM CLIENTES;
